-- Acceso seguro al panel privado del desarrollador.
-- Registrar el auth_user_id del desarrollador en developer_admins antes de usar el panel.

CREATE TABLE IF NOT EXISTS public.developer_admins (
    auth_user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre text,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.developer_admins ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.admin_auditoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_auth_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    accion text NOT NULL,
    empresa_id uuid REFERENCES public.empresas(id) ON DELETE SET NULL,
    usuario_id bigint REFERENCES public.usuarios(id) ON DELETE SET NULL,
    detalle jsonb NOT NULL DEFAULT '{}'::jsonb,
    creado_en timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.admin_auditoria ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.admin_suscripciones (
    empresa_id uuid PRIMARY KEY REFERENCES public.empresas(id) ON DELETE CASCADE,
    plan text NOT NULL DEFAULT 'prueba',
    estado text NOT NULL DEFAULT 'prueba',
    fecha_inicio timestamptz NOT NULL DEFAULT now(),
    fecha_vencimiento timestamptz,
    limite_usuarios integer NOT NULL DEFAULT 5,
    limite_productos integer NOT NULL DEFAULT 500,
    actualizado_en timestamptz NOT NULL DEFAULT now(),
    CHECK (plan IN ('prueba', 'basico', 'profesional', 'empresarial')),
    CHECK (estado IN ('prueba', 'activa', 'vencida', 'cancelada'))
);

ALTER TABLE public.admin_suscripciones ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.admin_pagos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id uuid NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    monto numeric(14,2) NOT NULL CHECK (monto >= 0),
    moneda text NOT NULL DEFAULT 'PYG',
    metodo text NOT NULL DEFAULT 'transferencia',
    estado text NOT NULL DEFAULT 'pendiente',
    fecha_pago date NOT NULL DEFAULT current_date,
    comprobante_url text,
    nota text,
    registrado_por uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    creado_en timestamptz NOT NULL DEFAULT now(),
    CHECK (metodo IN ('transferencia', 'efectivo', 'tarjeta', 'otro')),
    CHECK (estado IN ('pendiente', 'aprobado', 'rechazado'))
);

ALTER TABLE public.admin_pagos ENABLE ROW LEVEL SECURITY;

INSERT INTO public.admin_suscripciones (empresa_id, fecha_vencimiento)
SELECT id, now() + interval '30 days'
FROM public.empresas
ON CONFLICT (empresa_id) DO NOTHING;

ALTER TABLE public.empresas
    ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT 'activa';

UPDATE public.empresas
SET estado = 'activa'
WHERE estado IS NULL OR estado NOT IN ('activa', 'suspendida');

CREATE OR REPLACE FUNCTION public.admin_es_desarrollador()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
    SELECT EXISTS (
        SELECT 1
        FROM public.developer_admins
        WHERE auth_user_id = auth.uid()
          AND activo = true
    );
$function$;

CREATE OR REPLACE FUNCTION public.consultar_limites_empresa(p_empresa_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
    suscripcion public.admin_suscripciones%ROWTYPE;
    resultado jsonb;
BEGIN
    IF mi_empresa_id() IS DISTINCT FROM p_empresa_id THEN
        RAISE EXCEPTION 'Empresa no autorizada';
    END IF;

    SELECT * INTO suscripcion
    FROM public.admin_suscripciones
    WHERE empresa_id = p_empresa_id;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('usuarios', 0, 'productos', 0, 'limite_usuarios', 5, 'limite_productos', 500);
    END IF;

    SELECT jsonb_build_object(
        'usuarios', (SELECT count(*) FROM public.usuarios WHERE empresa_id = p_empresa_id),
        'productos', (SELECT count(*) FROM public.productos WHERE empresa_id = p_empresa_id),
        'limite_usuarios', suscripcion.limite_usuarios,
        'limite_productos', suscripcion.limite_productos,
        'plan', suscripcion.plan,
        'estado', suscripcion.estado
    ) INTO resultado;
    RETURN resultado;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_registrar_auditoria(
    p_accion text,
    p_empresa_id uuid DEFAULT NULL,
    p_usuario_id bigint DEFAULT NULL,
    p_detalle jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    INSERT INTO public.admin_auditoria (admin_auth_user_id, accion, empresa_id, usuario_id, detalle)
    VALUES (auth.uid(), p_accion, p_empresa_id, p_usuario_id, COALESCE(p_detalle, '{}'::jsonb));
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_listar_auditoria()
RETURNS TABLE (
    id bigint,
    accion text,
    empresa_id uuid,
    usuario_id bigint,
    detalle jsonb,
    creado_en timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    RETURN QUERY
    SELECT a.id, a.accion, a.empresa_id, a.usuario_id, a.detalle, a.creado_en
    FROM public.admin_auditoria a
    ORDER BY a.creado_en DESC
    LIMIT 50;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_listar_pagos()
RETURNS TABLE (
    id bigint,
    empresa_id uuid,
    empresa text,
    monto numeric,
    moneda text,
    metodo text,
    estado text,
    fecha_pago date,
    comprobante_url text,
    nota text,
    creado_en timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    RETURN QUERY
    SELECT p.id, p.empresa_id, e.nombre, p.monto, p.moneda, p.metodo,
           p.estado, p.fecha_pago, p.comprobante_url, p.nota, p.creado_en
    FROM public.admin_pagos p
    JOIN public.empresas e ON e.id = p.empresa_id
    ORDER BY p.creado_en DESC
    LIMIT 100;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_registrar_pago(
    p_empresa_id uuid,
    p_monto numeric,
    p_moneda text,
    p_metodo text,
    p_fecha_pago date,
    p_comprobante_url text DEFAULT NULL,
    p_nota text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
    pago_id bigint;
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    IF p_monto IS NULL OR p_monto < 0 THEN
        RAISE EXCEPTION 'El monto del pago no es válido';
    END IF;

    INSERT INTO public.admin_pagos (empresa_id, monto, moneda, metodo, fecha_pago, comprobante_url, nota, registrado_por)
    VALUES (p_empresa_id, p_monto, COALESCE(NULLIF(trim(p_moneda), ''), 'PYG'), p_metodo, COALESCE(p_fecha_pago, current_date), p_comprobante_url, p_nota, auth.uid())
    RETURNING id INTO pago_id;

    PERFORM public.admin_registrar_auditoria('registrar_pago', p_empresa_id, NULL, jsonb_build_object('pago_id', pago_id, 'monto', p_monto, 'estado', 'pendiente'));
    RETURN pago_id;
END;
$function$;

DROP FUNCTION IF EXISTS public.admin_listar_suscripciones();

CREATE OR REPLACE FUNCTION public.admin_listar_suscripciones()
RETURNS TABLE (
    empresa_id uuid,
    empresa text,
    plan text,
    estado text,
    fecha_vencimiento timestamptz,
    usuarios bigint,
    productos bigint,
    limite_usuarios integer,
    limite_productos integer
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    RETURN QUERY
    SELECT s.empresa_id, e.nombre,
           s.plan,
           CASE
               WHEN s.fecha_vencimiento IS NOT NULL
                AND s.fecha_vencimiento < now()
                AND s.estado IN ('prueba', 'activa') THEN 'vencida'
               ELSE s.estado
           END AS estado,
           s.fecha_vencimiento,
           (SELECT count(*)::bigint FROM public.usuarios u WHERE u.empresa_id = e.id),
           (SELECT count(*)::bigint FROM public.productos p WHERE p.empresa_id = e.id),
           s.limite_usuarios, s.limite_productos
    FROM public.admin_suscripciones s
    JOIN public.empresas e ON e.id = s.empresa_id
    ORDER BY s.fecha_vencimiento NULLS LAST, e.nombre;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_actualizar_suscripcion(
    p_empresa_id uuid,
    p_plan text,
    p_estado text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    IF p_plan NOT IN ('prueba', 'basico', 'profesional', 'empresarial')
       OR p_estado NOT IN ('prueba', 'activa', 'vencida', 'cancelada') THEN
        RAISE EXCEPTION 'Plan o estado de suscripción no válido';
    END IF;

    UPDATE public.admin_suscripciones
    SET plan = p_plan,
        estado = p_estado,
        limite_usuarios = CASE p_plan
            WHEN 'prueba' THEN 5
            WHEN 'basico' THEN 10
            WHEN 'profesional' THEN 25
            WHEN 'empresarial' THEN 100
        END,
        limite_productos = CASE p_plan
            WHEN 'prueba' THEN 500
            WHEN 'basico' THEN 2000
            WHEN 'profesional' THEN 10000
            WHEN 'empresarial' THEN 50000
        END,
        actualizado_en = now()
    WHERE empresa_id = p_empresa_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Suscripción no encontrada';
    END IF;

    PERFORM public.admin_registrar_auditoria('actualizar_suscripcion', p_empresa_id, NULL, jsonb_build_object('plan', p_plan, 'estado', p_estado));
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_actualizar_suscripcion_completa(
    p_empresa_id uuid,
    p_plan text,
    p_estado text,
    p_fecha_vencimiento timestamptz DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    IF p_plan NOT IN ('prueba', 'basico', 'profesional', 'empresarial')
       OR p_estado NOT IN ('prueba', 'activa', 'vencida', 'cancelada') THEN
        RAISE EXCEPTION 'Plan o estado de suscripción no válido';
    END IF;

    UPDATE public.admin_suscripciones
    SET plan = p_plan,
        estado = p_estado,
        fecha_vencimiento = p_fecha_vencimiento,
        limite_usuarios = CASE p_plan
            WHEN 'prueba' THEN 5
            WHEN 'basico' THEN 10
            WHEN 'profesional' THEN 25
            WHEN 'empresarial' THEN 100
        END,
        limite_productos = CASE p_plan
            WHEN 'prueba' THEN 500
            WHEN 'basico' THEN 2000
            WHEN 'profesional' THEN 10000
            WHEN 'empresarial' THEN 50000
        END,
        actualizado_en = now()
    WHERE empresa_id = p_empresa_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Suscripción no encontrada';
    END IF;

    PERFORM public.admin_registrar_auditoria('actualizar_suscripcion', p_empresa_id, NULL, jsonb_build_object('plan', p_plan, 'estado', p_estado, 'fecha_vencimiento', p_fecha_vencimiento));
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_resumen_desarrollador()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    RETURN jsonb_build_object(
        'empresas', (SELECT count(*) FROM public.empresas),
        'usuarios', (SELECT count(*) FROM public.usuarios),
        'usuarios_activos', (SELECT count(*) FROM public.usuarios WHERE activo = true AND permitir_acceso = true),
        'productos', (SELECT count(*) FROM public.productos),
        'clientes', (SELECT count(*) FROM public.clientes),
        'ventas', (SELECT count(*) FROM public.ventas),
        'compras', (SELECT count(*) FROM public.compras)
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_reporte_ventas(
    p_desde date,
    p_hasta date
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
    resultado jsonb;
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    IF p_desde IS NULL OR p_hasta IS NULL OR p_desde > p_hasta THEN
        RAISE EXCEPTION 'Rango de fechas no válido';
    END IF;

    WITH ventas_filtradas AS (
        SELECT v.*
        FROM public.ventas v
        WHERE COALESCE(v.fecha, v.creado_en) >= p_desde::timestamptz
          AND COALESCE(v.fecha, v.creado_en) < (p_hasta + 1)::timestamptz
    ),
    resumen AS (
        SELECT
            count(*)::bigint AS cantidad_ventas,
            COALESCE(sum(total), 0)::numeric AS ingresos,
            COALESCE(sum(monto_pagado), 0)::numeric AS cobrado,
            COALESCE(sum(saldo_pendiente), 0)::numeric AS pendiente
        FROM ventas_filtradas
    ),
    ganancias AS (
        SELECT COALESCE(sum(
            (dv.precio_unitario * dv.cantidad)
            - (dv.precio_costo * dv.cantidad)
            - COALESCE(dv.descuento, 0)
            + COALESCE(dv.impuesto, 0)
        ), 0)::numeric AS ganancia
        FROM public.detalle_ventas dv
        JOIN ventas_filtradas v ON v.id = dv.venta_id
    ),
    por_cliente AS (
        SELECT
            COALESCE(NULLIF(trim(v.cliente), ''), 'Sin cliente') AS cliente,
            count(*)::bigint AS ventas,
            COALESCE(sum(v.total), 0)::numeric AS ingresos,
            COALESCE(sum(dv.ganancia), 0)::numeric AS ganancia
        FROM ventas_filtradas v
        LEFT JOIN (
            SELECT venta_id, sum(
                (precio_unitario * cantidad)
                - (precio_costo * cantidad)
                - COALESCE(descuento, 0)
                + COALESCE(impuesto, 0)
            ) AS ganancia
            FROM public.detalle_ventas
            GROUP BY venta_id
        ) dv ON dv.venta_id = v.id
        GROUP BY COALESCE(NULLIF(trim(v.cliente), ''), 'Sin cliente')
        ORDER BY ingresos DESC
    )
    SELECT jsonb_build_object(
        'desde', p_desde,
        'hasta', p_hasta,
        'resumen', (SELECT jsonb_build_object(
            'cantidad_ventas', r.cantidad_ventas,
            'ingresos', r.ingresos,
            'cobrado', r.cobrado,
            'pendiente', r.pendiente,
            'ganancia', g.ganancia
        ) FROM resumen r CROSS JOIN ganancias g),
        'clientes', COALESCE((SELECT jsonb_agg(to_jsonb(c)) FROM por_cliente c), '[]'::jsonb)
    ) INTO resultado;

    RETURN resultado;
END;
$function$;

DROP FUNCTION IF EXISTS public.admin_listar_empresas();

CREATE OR REPLACE FUNCTION public.admin_listar_empresas()
RETURNS TABLE (
    id uuid,
    nombre text,
    email text,
    telefono text,
    creado_en timestamptz,
    estado text,
    usuarios bigint
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    RETURN QUERY
    SELECT
        e.id,
        e.nombre,
        COALESCE(min(u.email), '')::text AS email,
        COALESCE(min(u.telefono_movil), '')::text AS telefono,
        e.creado_en,
        e.estado,
        count(u.id)::bigint AS usuarios
    FROM public.empresas e
    LEFT JOIN public.usuarios u ON u.empresa_id = e.id
    GROUP BY e.id, e.nombre, e.creado_en, e.estado
    ORDER BY e.creado_en DESC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_detalle_empresa(p_empresa_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
    resultado jsonb;
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    SELECT jsonb_build_object(
        'empresa', jsonb_build_object(
            'id', e.id,
            'nombre', e.nombre,
            'direccion', e.direccion,
            'telefono', e.telefono,
            'creado_en', e.creado_en,
            'estado', e.estado
        ),
        'usuarios', COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
                'id', u.id,
                'nombre', u.nombre,
                'apellido', u.apellido,
                'email', u.email,
                'activo', u.activo,
                'permitir_acceso', u.permitir_acceso
            ) ORDER BY u.nombre)
            FROM public.usuarios u
            WHERE u.empresa_id = e.id
        ), '[]'::jsonb)
    )
    INTO resultado
    FROM public.empresas e
    WHERE e.id = p_empresa_id;

    IF resultado IS NULL THEN
        RAISE EXCEPTION 'Empresa no encontrada';
    END IF;

    RETURN resultado;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_actualizar_empresa(
    p_empresa_id uuid,
    p_nombre text,
    p_direccion text,
    p_telefono text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    IF NULLIF(trim(p_nombre), '') IS NULL THEN
        RAISE EXCEPTION 'El nombre de la empresa es obligatorio';
    END IF;

    UPDATE public.empresas
    SET nombre = trim(p_nombre),
        direccion = NULLIF(trim(p_direccion), ''),
        telefono = NULLIF(trim(p_telefono), '')
    WHERE id = p_empresa_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Empresa no encontrada';
    END IF;

    PERFORM public.admin_registrar_auditoria('editar_empresa', p_empresa_id, NULL, jsonb_build_object('nombre', trim(p_nombre)));
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_cambiar_estado_empresa(
    p_empresa_id uuid,
    p_estado text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    IF p_estado NOT IN ('activa', 'suspendida') THEN
        RAISE EXCEPTION 'Estado de empresa no válido';
    END IF;

    UPDATE public.empresas
    SET estado = p_estado
    WHERE id = p_empresa_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Empresa no encontrada';
    END IF;

    PERFORM public.admin_registrar_auditoria('cambiar_estado_empresa', p_empresa_id, NULL, jsonb_build_object('estado', p_estado));
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_cambiar_acceso_usuario(
    p_usuario_id bigint,
    p_permitir_acceso boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
    IF NOT public.admin_es_desarrollador() THEN
        RAISE EXCEPTION 'Acceso reservado al desarrollador';
    END IF;

    UPDATE public.usuarios
    SET activo = p_permitir_acceso,
        permitir_acceso = p_permitir_acceso
    WHERE id = p_usuario_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Usuario no encontrado';
    END IF;

    PERFORM public.admin_registrar_auditoria('cambiar_acceso_usuario', NULL, p_usuario_id, jsonb_build_object('permitir_acceso', p_permitir_acceso));
END;
$function$;

REVOKE ALL ON FUNCTION public.admin_es_desarrollador() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.consultar_limites_empresa(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_registrar_auditoria(text, uuid, bigint, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_listar_auditoria() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_listar_pagos() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_registrar_pago(uuid, numeric, text, text, date, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_listar_suscripciones() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_actualizar_suscripcion(uuid, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_actualizar_suscripcion_completa(uuid, text, text, timestamptz) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_resumen_desarrollador() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_reporte_ventas(date, date) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_listar_empresas() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_detalle_empresa(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_cambiar_acceso_usuario(bigint, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_cambiar_estado_empresa(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_actualizar_empresa(uuid, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_es_desarrollador() TO authenticated;
GRANT EXECUTE ON FUNCTION public.consultar_limites_empresa(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_registrar_auditoria(text, uuid, bigint, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_listar_auditoria() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_listar_pagos() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_registrar_pago(uuid, numeric, text, text, date, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_listar_suscripciones() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_actualizar_suscripcion(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_actualizar_suscripcion_completa(uuid, text, text, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_resumen_desarrollador() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_reporte_ventas(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_listar_empresas() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_detalle_empresa(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cambiar_acceso_usuario(bigint, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cambiar_estado_empresa(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_actualizar_empresa(uuid, text, text, text) TO authenticated;
