import { createContext, useContext, useEffect, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'pypos-language';

const translations = {
  es: {
    language: 'Idioma',
    spanish: 'Español',
    portuguese: 'Português (Brasil)',
    english: 'English (United States)',
    loading: 'Cargando...',
    login: 'Iniciar sesión',
    email: 'Correo electrónico *',
    password: 'Contraseña *',
    remember: 'Recuérdame',
    forgotPassword: '¿Olvidaste tu contraseña?',
    validating: 'Validando...',
    loginButton: 'INICIAR SESIÓN',
    newBusiness: '¿Sos un negocio nuevo? Creá tu cuenta',
    createAccountHere: 'Creá tu cuenta acá.',
    home: 'Inicio',
    pos: 'Punto de Venta',
    workOrders: 'OT',
    userManagement: 'Gestión de usuarios',
    users: 'Usuarios',
    roles: 'Roles',
    contacts: 'Cliente/Proveedor',
    suppliers: 'Proveedores',
    customers: 'Clientes',
    customerGroups: 'Grupos de clientes',
    products: 'Productos',
    productList: 'Lista de productos',
    addProduct: 'Agregar producto',
    brands: 'Marcas',
    categories: 'Categorías',
    units: 'Unidades',
    purchases: 'Compras',
    purchaseList: 'Lista de compras',
    addPurchase: 'Agregar compra',
    purchaseReturns: 'Lista de devoluciones de compra',
    expenses: 'Gastos',
    expenseList: 'Lista de gastos',
    addExpense: 'Agregar gasto',
    expenseCategories: 'Categorías de gastos',
    sales: 'Ventas',
    allSales: 'Todas las ventas',
    pendingOrders: 'Pedidos pendientes',
    cashBank: 'Caja / Banco',
    cashRegisters: 'Lista de cajas',
    paymentReport: 'Informe de caja de pago',
    reports: 'Informes',
    profitLoss: 'Ganancias y Pérdidas',
    salesByProduct: 'Ventas por producto',
    salesCollections: 'Cobros de venta',
    cashRegister: 'Caja registradora',
    sellersCommissions: 'Vendedores / Comisiones',
    settings: 'Configuraciones',
    companySettings: 'Configuración de la empresa',
    commercialLocations: 'Ubicaciones comerciales',
    invoiceSettings: 'Configuración de factura',
    logout: 'Cerrar sesión',
    notifications: 'Notificaciones',
    realtimeData: 'Datos en tiempo real',
    noNotifications: 'No hay notificaciones nuevas.',
    purchasePending: 'Compra pendiente',
    openRegister: 'Caja abierta',
    openedBy: 'Abierta por',
    registerOpen: 'Hay una caja abierta',
    lowStock: 'Stock bajo',
    unitsLabel: 'unidades',
    collapseMenu: 'Colapsar menú',
    expandMenu: 'Expandir menú',
    notificationLabel: 'Notificaciones',
    manageCustomers: 'Administra tus clientes',
    filters: 'Filtros',
    creditGranted: 'Créditos otorgados',
    salesReturn: 'Devolución de venta',
    paymentCompleted: 'Pago realizado',
    creditBalance: 'Crédito a favor',
    customerGroup: 'Grupo de clientes',
    status: 'Estado',
    allCustomers: 'Todos sus clientes',
    add: 'Añadir',
    show: 'Mostrar',
    entries: 'entradas',
    exportCsv: 'Exportar a CSV',
    exportExcel: 'Exportar a Excel',
    exportPdf: 'Exportar a PDF',
    print: 'Imprimir',
    search: 'Buscar',
    noData: 'No hay datos disponibles en la tabla',
    companyLocation: 'Ubicación de la empresa',
    purchaseStatus: 'Estado de compra',
    paymentStatus: 'Estado de pago',
    allPurchases: 'Todas las compras',
    backToList: 'Volver a la lista',
    registerNewPurchase: 'Registrar nueva compra',
    selectProduct: 'Seleccionar repuesto',
    saveAndAddStock: 'Guardar y sumar stock',
    noPurchases: 'No hay compras registradas.',
    allLocations: 'Todas las ubicaciones',
    dateRange: 'Rango de fechas',
    allExpenses: 'Todos los gastos',
    searchProduct: 'Buscar producto',
    customerGroupName: 'Nombre del grupo de clientes',
    all: 'Todos',
    electronicInvoicing: 'Configuración de facturación electrónica',
    loadingSellers: 'Cargando vendedores y comisiones...',
    manageUsers: 'Administrar usuarios',
    allUsers: 'Todos los usuarios',
    username: 'Nombre de usuario',
    name: 'Nombre',
    role: 'Rol',
    saveUser: 'Guardar usuario',
    loadingUsers: 'Cargando usuarios...',
    view: 'Ver',
    delete: 'Borrar',
    previous: 'Anterior',
    next: 'Siguiente',
    userAdded: 'Usuario agregado correctamente',
    userDeleted: 'Usuario eliminado correctamente.',
    saveError: 'Hubo un error al guardar. Verificá la consola.',
    deleteError: 'Hubo un error al eliminar el usuario',
    cancel: 'Cancelar',
    columnVisibility: 'Visibilidad de columnas',
    action: 'Acción',
    edit: 'Editar',
    showing: 'Mostrando',
    to: 'a',
    of: 'de',
    manageRoles: 'Gestionar roles',
    allRoles: 'Todos los roles',
    noRoles: 'No hay roles registrados.',
    roleNameRequired: 'El nombre del rol es obligatorio.',
    roleUpdated: '¡Rol actualizado con éxito!',
    roleCreated: '¡Rol creado con éxito!',
    saveRoleError: 'Error al guardar el rol',
    editRole: 'Editar rol',
    addRole: 'Agregar rol',
    roleName: 'Nombre del rol',
    roleExample: 'Ej: Cajero',
    descriptionOptional: 'Descripción (opcional)',
    selectAll: 'Seleccionar todo',
    saving: 'Guardando...',
    save: 'Guardar',
    editUser: 'Editar usuario',
    addUser: 'Agregar usuario',
    titleExample: 'Señor, señora',
    isActive: '¿Está activo?',
    allowAccess: 'Permitir acceso',
    confirmPassword: 'Confirmar contraseña',
    accessLocations: 'Lugares de acceso',
    fixedBranch: 'Sucursal fija',
    branchAccessHelp: 'Este usuario solo verá el stock, las ventas y la caja de esta sucursal.',
    select: 'Seleccione',
    salesCommissionPercentage: 'Porcentaje de la comisión de ventas (%)',
    maxSalesDiscountPercentage: 'Porcentaje máximo de descuento de ventas',
    allowSelectedContacts: 'Permitir contactos seleccionados',
    bankDetails: 'Detalles del banco',
    hrDetails: 'Detalles de gestión de recursos humanos',
    restrictedAccess: 'Acceso restringido',
    noModulePermission: 'Tu rol no tiene permiso para acceder a este módulo.',
    backHome: 'Volver al inicio',
    checkingOpenRegister: 'Verificando caja abierta...',
    loadingData: 'Cargando datos reales...', businessSummary: 'Resumen de tu negocio', totalSales: 'Ventas totales', profit: 'Utilidad', salesMinusCosts: 'ventas - compras - gastos', billToPay: 'Factura a pagar', pendingSuppliers: 'pendiente a proveedores', period: 'del período', totalPurchases: 'Compras totales', purchaseDebt: 'Compra adeudada', creditsGranted: 'Créditos otorgados', openRegisters: 'Cajas abiertas', autoRefresh: 'Se actualiza sola cada 20 segundos - no hace falta recargar la página.', noOpenRegisters: 'No hay ninguna caja abierta en este momento.', forceCloseHelp: 'Cerrar esta caja si quedó abierta por error', forceClose: 'Forzar cierre', cash: 'Efectivo', card: 'Tarjeta',
    vsPreviousPeriod: 'vs período anterior', noSalesPeriod: 'No hay ventas en este período.', composition: 'Composición', noDataPeriod: 'Sin datos en este período.', salesPurchasesExpenses: 'Ventas vs Compras vs Gastos', topProducts: 'Top 5 productos', noDetailedSales: 'Aún no hay ventas con detalle en este período.', recommendations: 'Recomendaciones para tu negocio', currentFiscalYear: 'Año fiscal actual de ventas', accountsReceivable: 'Deudas por cobrar', accountsPayable: 'Deudas por pagar', noReceivables: 'No hay deudas por cobrar.', invoiceNumber: 'Factura No.', amountDue: 'Cantidad debida', noPayables: 'No hay deudas con proveedores.', invoice: 'Factura', amount: 'Monto', stockGood: 'Todo tu stock está en buen nivel.', stock: 'Stock',
    newCustomer: 'Nuevo cliente', searchProductSku: 'Introduzca el nombre del producto / SKU / código de barras', advancedOptions: 'Opciones avanzadas', discount: 'Descuento', packagingCharge: 'Cargo de embalaje', serviceSeller: 'Personal de servicio / vendedor', selectServiceSeller: 'Seleccionar personal de servicio', saleNote: 'Nota de venta', product: 'Producto', quantityShort: 'Cant.', unitPriceShort: 'P. Unit.', subtotal: 'Subtotal', emptyCart: 'El carrito está vacío', items: 'Artículos', total: 'Total', paidWith: 'Paga con', paymentMethod: 'Método de pago', transferShort: 'Transf.', charge: 'Cobrar', change: 'Vuelto', remainingDebt: 'Queda debiendo', pendingOrder: 'Pedido pendiente', quote: 'Cotización', creditSale: 'Venta a crédito', multiplePayment: 'Pago múltiple',
    productType: 'Tipo de producto', stockStatus: 'Estado del stock', withStock: 'Con stock', withoutStock: 'Sin stock', lowStockThreshold: 'Stock bajo (bajo umbral de alerta)', notForSale: 'No para vender', onlyBelowAlert: 'Solo bajo umbral de alerta', min: 'mín.', max: 'máx.', woocommerceEnabled: 'Woocommerce habilitado', image: 'Imagen', unitPurchasePrice: 'Precio de compra unitario', salePrice: 'Precio de venta', currentStock: 'Stock actual', noMatchingProducts: 'Ningún producto coincide con los criterios de búsqueda.', labels: 'Etiquetas', initialStock: 'Agregar o editar stock inicial', stockHistory: 'Historial de existencias', groupPrices: 'Precios de grupo', duplicateProduct: 'Producto duplicado', noProductMovements: 'Este producto todavía no tiene ventas ni compras registradas.', productUpdated: '¡Producto actualizado con éxito!', productSaved: '¡Producto guardado con éxito!', editProduct: 'Editar producto', addNewProduct: 'Agregar nuevo producto', productInformation: 'Información del producto', productName: 'Nombre del producto', skuBarcodeType: 'SKU/Código de barra / Tipo de código de barras', select: 'Seleccione', subcategory: 'Subcategoría', warranty: 'Garantía', selectAvailableLocations: 'Seleccione en qué sucursales estará disponible',
    birthDate: 'Fecha de nacimiento', gender: 'Género', maritalStatus: 'Estado civil', bloodType: 'Grupo sanguíneo', mobilePhone: 'Número de teléfono móvil', dataAndType: 'Datos y tipo (descripción, folleto, stock)', productDescription: 'Descripción del producto', productBrochure: 'Folleto del producto', selectFile: 'Seleccionar archivo', noFileSelected: 'Ningún archivo seleccionado', stockAndAlerts: 'Stock y alertas', manageStockQuestion: '¿Administrar stock?', yes: 'Sí', alertQuantity: 'Cantidad para alerta', expiresIn: 'Expira en', pricesAndTaxes: 'Precios e impuestos', applicableTax: 'Impuesto aplicable', salePriceTaxType: 'Tipo de impuesto sobre el precio de venta', defaultPurchasePrice: 'Precio de compra predeterminado', defaultSalePrice: 'Precio de venta predeterminado', taxNotIncluded: 'IVA no incluido', taxIncluded: 'IVA incluido',
    manageSuppliers: 'Administra tus proveedores', purchaseReturn: 'Devolución de compra', seller: 'Vendedor', allSuppliers: 'Todos sus proveedores', loadingSuppliers: 'Cargando proveedores...', noSuppliers: 'No se encontraron proveedores.', actions: 'Acciones', editSupplier: 'Editar proveedor', addSupplier: 'Añadir proveedor', contactType: 'Tipo de contacto', bothContacts: 'Ambos (Proveedor y Cliente)', companyName: 'Nombre de la empresa', representativeName: 'Nombre del representante', documentNumber: 'Documento N°', paymentTermDays: 'Término de pago (días)', openingBalance: 'Saldo de apertura', address: 'Dirección', supplierDetails: 'Detalle del proveedor', code: 'Código', company: 'Empresa', representative: 'Representante', paymentTerm: 'Término de pago', days: 'días', saveChanges: 'Guardar cambios',
    salesPos: 'Ventas / Punto de venta',
    viewCustomers: 'Ver clientes', addCustomer: 'Agregar cliente', editCustomer: 'Editar cliente', deleteCustomer: 'Borrar cliente',
    viewSuppliers: 'Ver proveedores', addSupplier: 'Agregar proveedor', editSupplier: 'Editar proveedor', deleteSupplier: 'Borrar proveedor',
    viewUsers: 'Ver usuarios', addUserPermission: 'Agregar usuario', editUserPermission: 'Editar usuario', deleteUserPermission: 'Borrar usuario',
    viewRoles: 'Ver roles', addRolePermission: 'Agregar rol', editRolePermission: 'Editar rol', deleteRolePermission: 'Borrar rol',
    viewProducts: 'Ver productos', addProductPermission: 'Agregar producto', editProductPermission: 'Editar producto', deleteProductPermission: 'Borrar producto', viewBrands: 'Ver marcas', viewUnits: 'Ver unidades', viewPurchasePrices: 'Ver precios de compra',
    viewPurchases: 'Ver compras', addPurchasePermission: 'Agregar compra', editPurchasePermission: 'Editar compra', deletePurchasePermission: 'Borrar compra', viewSupplierDebts: 'Ver deudas a proveedores',
    accessPos: 'Acceder al Punto de Venta', posOnly: 'Solo Punto de Venta (bloquea todo lo demás)', applyDiscounts: 'Aplicar descuentos', registerCreditSale: 'Registrar venta a crédito', editPrice: 'Editar precio manualmente', viewOtherSales: 'Ver ventas de otros usuarios',
    openCash: 'Abrir caja', closeCash: 'Cerrar caja', registerShiftExpenses: 'Registrar gastos del turno', viewCashHistory: 'Ver caja registradora (histórico)', viewExpenses: 'Ver gastos', addExpensePermission: 'Agregar gasto', viewProfitLoss: 'Ver Ganancias y Pérdidas', viewCashRegister: 'Ver Caja registradora', exportReports: 'Exportar reportes (CSV/Excel/PDF)', accessGeneralSettings: 'Acceso a configuraciones generales del sistema', viewWorkOrders: 'Ver órdenes de trabajo', createWorkOrder: 'Crear orden de trabajo', editWorkOrder: 'Editar orden de trabajo', deleteWorkOrder: 'Borrar orden de trabajo', viewLocations: 'Ver ubicaciones', manageLocations: 'Administrar ubicaciones',
    prefix: 'Prefijo',
    lastName: 'Apellido',
    rolesPermissions: 'Roles y permisos',
    usernameAuto: 'Dejar en blanco para generar automáticamente el nombre de usuario',
    financialData: 'Datos financieros',
    openCashRegister: 'Abrir caja registradora',
    enterOpeningBalance: 'Ingrese el saldo inicial en Caja',
    branch: 'Sucursal',
    selectBranch: 'Seleccione una sucursal',
    noBranchAssigned: 'Sin sucursal asignada',
    cashInBaseCurrency: 'Efectivo en moneda base',
    enterAmount: 'Ingresar cantidad',
    opening: 'Abriendo...',
    openRegisterButton: 'Abrir registro',
    dateLocale: 'es-PY',
  },
  pt: {
    language: 'Idioma',
    spanish: 'Español',
    portuguese: 'Português (Brasil)',
    english: 'English (United States)',
    loading: 'Carregando...',
    login: 'Entrar',
    email: 'E-mail *',
    password: 'Senha *',
    remember: 'Lembrar de mim',
    forgotPassword: 'Esqueceu sua senha?',
    validating: 'Validando...',
    loginButton: 'ENTRAR',
    newBusiness: 'É um negócio novo? Crie sua conta',
    createAccountHere: 'Crie sua conta aqui.',
    home: 'Início',
    pos: 'Ponto de Venda',
    workOrders: 'OS',
    userManagement: 'Gestão de usuários',
    users: 'Usuários',
    roles: 'Funções',
    contacts: 'Cliente/Fornecedor',
    suppliers: 'Fornecedores',
    customers: 'Clientes',
    customerGroups: 'Grupos de clientes',
    products: 'Produtos',
    productList: 'Lista de produtos',
    addProduct: 'Adicionar produto',
    brands: 'Marcas',
    categories: 'Categorias',
    units: 'Unidades',
    purchases: 'Compras',
    purchaseList: 'Lista de compras',
    addPurchase: 'Adicionar compra',
    purchaseReturns: 'Lista de devoluções de compra',
    expenses: 'Despesas',
    expenseList: 'Lista de despesas',
    addExpense: 'Adicionar despesa',
    expenseCategories: 'Categorias de despesas',
    sales: 'Vendas',
    allSales: 'Todas as vendas',
    pendingOrders: 'Pedidos pendentes',
    cashBank: 'Caixa / Banco',
    cashRegisters: 'Lista de caixas',
    paymentReport: 'Relatório de caixa de pagamento',
    reports: 'Relatórios',
    profitLoss: 'Lucros e Perdas',
    salesByProduct: 'Vendas por produto',
    salesCollections: 'Cobranças de vendas',
    cashRegister: 'Caixa registradora',
    sellersCommissions: 'Vendedores / Comissões',
    settings: 'Configurações',
    companySettings: 'Configuração da empresa',
    commercialLocations: 'Localizações comerciais',
    invoiceSettings: 'Configuração de faturamento',
    logout: 'Sair',
    notifications: 'Notificações',
    realtimeData: 'Dados em tempo real',
    noNotifications: 'Não há novas notificações.',
    purchasePending: 'Compra pendente',
    openRegister: 'Caixa aberto',
    openedBy: 'Aberto por',
    registerOpen: 'Há um caixa aberto',
    lowStock: 'Estoque baixo',
    unitsLabel: 'unidades',
    collapseMenu: 'Recolher menu',
    expandMenu: 'Expandir menu',
    notificationLabel: 'Notificações',
    manageCustomers: 'Administre seus clientes',
    filters: 'Filtros',
    creditGranted: 'Créditos concedidos',
    salesReturn: 'Devolução de venda',
    paymentCompleted: 'Pagamento realizado',
    creditBalance: 'Crédito a favor',
    customerGroup: 'Grupo de clientes',
    status: 'Status',
    allCustomers: 'Todos os seus clientes',
    add: 'Adicionar',
    show: 'Mostrar',
    entries: 'entradas',
    exportCsv: 'Exportar para CSV',
    exportExcel: 'Exportar para Excel',
    exportPdf: 'Exportar para PDF',
    print: 'Imprimir',
    search: 'Buscar',
    noData: 'Não há dados disponíveis na tabela',
    companyLocation: 'Localização da empresa',
    purchaseStatus: 'Status da compra',
    paymentStatus: 'Status do pagamento',
    allPurchases: 'Todas as compras',
    backToList: 'Voltar para a lista',
    registerNewPurchase: 'Registrar nova compra',
    selectProduct: 'Selecionar peça',
    saveAndAddStock: 'Salvar e adicionar estoque',
    noPurchases: 'Não há compras registradas.',
    allLocations: 'Todas as localizações',
    dateRange: 'Período',
    allExpenses: 'Todas as despesas',
    searchProduct: 'Buscar produto',
    customerGroupName: 'Nome do grupo de clientes',
    all: 'Todos',
    electronicInvoicing: 'Configuração de faturamento eletrônico',
    loadingSellers: 'Carregando vendedores e comissões...',
    manageUsers: 'Gerenciar usuários',
    allUsers: 'Todos os usuários',
    username: 'Nome de usuário',
    name: 'Nome',
    role: 'Função',
    saveUser: 'Salvar usuário',
    loadingUsers: 'Carregando usuários...',
    view: 'Ver',
    delete: 'Excluir',
    previous: 'Anterior',
    next: 'Próximo',
    userAdded: 'Usuário adicionado com sucesso',
    userDeleted: 'Usuário excluído com sucesso.',
    saveError: 'Ocorreu um erro ao salvar. Verifique o console.',
    deleteError: 'Ocorreu um erro ao excluir o usuário',
    cancel: 'Cancelar',
    columnVisibility: 'Visibilidade das colunas',
    action: 'Ação',
    edit: 'Editar',
    showing: 'Mostrando',
    to: 'a',
    of: 'de',
    manageRoles: 'Gerenciar funções',
    allRoles: 'Todas as funções',
    noRoles: 'Nenhuma função cadastrada.',
    roleNameRequired: 'O nome da função é obrigatório.',
    roleUpdated: 'Função atualizada com sucesso!',
    roleCreated: 'Função criada com sucesso!',
    saveRoleError: 'Erro ao salvar a função',
    editRole: 'Editar função',
    addRole: 'Adicionar função',
    roleName: 'Nome da função',
    roleExample: 'Ex.: Caixa',
    descriptionOptional: 'Descrição (opcional)',
    selectAll: 'Selecionar tudo',
    saving: 'Salvando...',
    save: 'Salvar',
    editUser: 'Editar usuário',
    addUser: 'Adicionar usuário',
    titleExample: 'Senhor, senhora',
    isActive: 'Está ativo?',
    allowAccess: 'Permitir acesso',
    confirmPassword: 'Confirmar senha',
    accessLocations: 'Locais de acesso',
    fixedBranch: 'Filial fixa',
    branchAccessHelp: 'Este usuário verá apenas o estoque, as vendas e o caixa desta filial.',
    select: 'Selecione',
    salesCommissionPercentage: 'Porcentagem da comissão de vendas (%)',
    maxSalesDiscountPercentage: 'Porcentagem máxima de desconto de vendas',
    allowSelectedContacts: 'Permitir contatos selecionados',
    bankDetails: 'Dados bancários',
    hrDetails: 'Detalhes de gestão de recursos humanos',
    restrictedAccess: 'Acesso restrito',
    noModulePermission: 'Sua função não tem permissão para acessar este módulo.',
    backHome: 'Voltar ao início',
    checkingOpenRegister: 'Verificando caixa aberta...',
    loadingData: 'Carregando dados reais...', businessSummary: 'Resumo do seu negócio', totalSales: 'Vendas totais', profit: 'Lucro', salesMinusCosts: 'vendas - compras - despesas', billToPay: 'Fatura a pagar', pendingSuppliers: 'pendente com fornecedores', period: 'do período', totalPurchases: 'Compras totais', purchaseDebt: 'Compra pendente', creditsGranted: 'Créditos concedidos', openRegisters: 'Caixas abertas', autoRefresh: 'Atualiza a cada 20 segundos - não é necessário recarregar a página.', noOpenRegisters: 'Não há nenhum caixa aberto no momento.', forceCloseHelp: 'Fechar este caixa se foi deixado aberto por engano', forceClose: 'Forçar fechamento', cash: 'Dinheiro', card: 'Cartão',
    vsPreviousPeriod: 'vs período anterior', noSalesPeriod: 'Não há vendas neste período.', composition: 'Composição', noDataPeriod: 'Sem dados neste período.', salesPurchasesExpenses: 'Vendas vs Compras vs Despesas', topProducts: 'Top 5 produtos', noDetailedSales: 'Ainda não há vendas detalhadas neste período.', recommendations: 'Recomendações para o seu negócio', currentFiscalYear: 'Ano fiscal atual de vendas', accountsReceivable: 'Contas a receber', accountsPayable: 'Contas a pagar', noReceivables: 'Não há contas a receber.', invoiceNumber: 'Nota fiscal Nº', amountDue: 'Valor devido', noPayables: 'Não há dívidas com fornecedores.', invoice: 'Nota fiscal', amount: 'Valor', stockGood: 'Todo o seu estoque está em bom nível.', stock: 'Estoque',
    newCustomer: 'Novo cliente', searchProductSku: 'Informe o nome do produto / SKU / código de barras', advancedOptions: 'Opções avançadas', discount: 'Desconto', packagingCharge: 'Taxa de embalagem', serviceSeller: 'Profissional de atendimento / vendedor', selectServiceSeller: 'Selecionar profissional de atendimento', saleNote: 'Observação da venda', product: 'Produto', quantityShort: 'Qtd.', unitPriceShort: 'P. Unit.', subtotal: 'Subtotal', emptyCart: 'O carrinho está vazio', items: 'Itens', total: 'Total', paidWith: 'Pago com', paymentMethod: 'Método de pagamento', transferShort: 'Transf.', charge: 'Cobrar', change: 'Troco', remainingDebt: 'Saldo devedor', pendingOrder: 'Pedido pendente', quote: 'Orçamento', creditSale: 'Venda a crédito', multiplePayment: 'Pagamento múltiplo',
    productType: 'Tipo de produto', stockStatus: 'Status do estoque', withStock: 'Com estoque', withoutStock: 'Sem estoque', lowStockThreshold: 'Estoque baixo (abaixo do limite de alerta)', notForSale: 'Não vender', onlyBelowAlert: 'Somente abaixo do limite de alerta', min: 'mín.', max: 'máx.', woocommerceEnabled: 'Woocommerce habilitado', image: 'Imagem', unitPurchasePrice: 'Preço de compra unitário', salePrice: 'Preço de venda', currentStock: 'Estoque atual', noMatchingProducts: 'Nenhum produto corresponde aos critérios de busca.', labels: 'Etiquetas', initialStock: 'Adicionar ou editar estoque inicial', stockHistory: 'Histórico de estoque', groupPrices: 'Preços por grupo', duplicateProduct: 'Duplicar produto', noProductMovements: 'Este produto ainda não possui vendas ou compras registradas.', productUpdated: 'Produto atualizado com sucesso!', productSaved: 'Produto salvo com sucesso!', editProduct: 'Editar produto', addNewProduct: 'Adicionar novo produto', productInformation: 'Informações do produto', productName: 'Nome do produto', skuBarcodeType: 'SKU/Código de barras / Tipo de código de barras', select: 'Selecione', subcategory: 'Subcategoria', warranty: 'Garantia', selectAvailableLocations: 'Selecione em quais filiais estará disponível',
    birthDate: 'Data de nascimento', gender: 'Gênero', maritalStatus: 'Estado civil', bloodType: 'Tipo sanguíneo', mobilePhone: 'Número de telefone celular', dataAndType: 'Dados e tipo (descrição, folheto, estoque)', productDescription: 'Descrição do produto', productBrochure: 'Folheto do produto', selectFile: 'Selecionar arquivo', noFileSelected: 'Nenhum arquivo selecionado', stockAndAlerts: 'Estoque e alertas', manageStockQuestion: 'Gerenciar estoque?', yes: 'Sim', alertQuantity: 'Quantidade para alerta', expiresIn: 'Expira em', pricesAndTaxes: 'Preços e impostos', applicableTax: 'Imposto aplicável', salePriceTaxType: 'Tipo de imposto sobre o preço de venda', defaultPurchasePrice: 'Preço de compra padrão', defaultSalePrice: 'Preço de venda padrão', taxNotIncluded: 'IVA não incluído', taxIncluded: 'IVA incluído',
    manageSuppliers: 'Gerencie seus fornecedores', purchaseReturn: 'Devolução de compra', seller: 'Vendedor', allSuppliers: 'Todos os seus fornecedores', loadingSuppliers: 'Carregando fornecedores...', noSuppliers: 'Nenhum fornecedor encontrado.', actions: 'Ações', editSupplier: 'Editar fornecedor', addSupplier: 'Adicionar fornecedor', contactType: 'Tipo de contato', bothContacts: 'Ambos (Fornecedor e Cliente)', companyName: 'Nome da empresa', representativeName: 'Nome do representante', documentNumber: 'Documento Nº', paymentTermDays: 'Prazo de pagamento (dias)', openingBalance: 'Saldo inicial', address: 'Endereço', supplierDetails: 'Detalhes do fornecedor', code: 'Código', company: 'Empresa', representative: 'Representante', paymentTerm: 'Prazo de pagamento', days: 'dias', saveChanges: 'Salvar alterações',
    salesPos: 'Vendas / Ponto de venda',
    viewCustomers: 'Ver clientes', addCustomer: 'Adicionar cliente', editCustomer: 'Editar cliente', deleteCustomer: 'Excluir cliente', viewSuppliers: 'Ver fornecedores', addSupplier: 'Adicionar fornecedor', editSupplier: 'Editar fornecedor', deleteSupplier: 'Excluir fornecedor', viewUsers: 'Ver usuários', addUserPermission: 'Adicionar usuário', editUserPermission: 'Editar usuário', deleteUserPermission: 'Excluir usuário', viewRoles: 'Ver funções', addRolePermission: 'Adicionar função', editRolePermission: 'Editar função', deleteRolePermission: 'Excluir função', viewProducts: 'Ver produtos', addProductPermission: 'Adicionar produto', editProductPermission: 'Editar produto', deleteProductPermission: 'Excluir produto', viewBrands: 'Ver marcas', viewUnits: 'Ver unidades', viewPurchasePrices: 'Ver preços de compra', viewPurchases: 'Ver compras', addPurchasePermission: 'Adicionar compra', editPurchasePermission: 'Editar compra', deletePurchasePermission: 'Excluir compra', viewSupplierDebts: 'Ver dívidas com fornecedores', accessPos: 'Acessar o Ponto de Venda', posOnly: 'Somente Ponto de Venda (bloqueia todo o resto)', applyDiscounts: 'Aplicar descontos', registerCreditSale: 'Registrar venda a crédito', editPrice: 'Editar preço manualmente', viewOtherSales: 'Ver vendas de outros usuários', openCash: 'Abrir caixa', closeCash: 'Fechar caixa', registerShiftExpenses: 'Registrar despesas do turno', viewCashHistory: 'Ver caixa registradora (histórico)', viewExpenses: 'Ver despesas', addExpensePermission: 'Adicionar despesa', viewProfitLoss: 'Ver Lucros e Perdas', viewCashRegister: 'Ver caixa registradora', exportReports: 'Exportar relatórios (CSV/Excel/PDF)', accessGeneralSettings: 'Acesso às configurações gerais do sistema', viewWorkOrders: 'Ver ordens de trabalho', createWorkOrder: 'Criar ordem de trabalho', editWorkOrder: 'Editar ordem de trabalho', deleteWorkOrder: 'Excluir ordem de trabalho', viewLocations: 'Ver localizações', manageLocations: 'Gerenciar localizações',
    prefix: 'Prefixo',
    lastName: 'Sobrenome',
    rolesPermissions: 'Funções e permissões',
    usernameAuto: 'Deixe em branco para gerar o nome de usuário automaticamente',
    financialData: 'Dados financeiros',
    openCashRegister: 'Abrir caixa registradora',
    enterOpeningBalance: 'Informe o saldo inicial do caixa',
    branch: 'Filial',
    selectBranch: 'Selecione uma filial',
    noBranchAssigned: 'Nenhuma filial atribuída',
    cashInBaseCurrency: 'Dinheiro na moeda base',
    enterAmount: 'Informe o valor',
    opening: 'Abrindo...',
    openRegisterButton: 'Abrir caixa',
    dateLocale: 'pt-BR',
  },
  en: {
    language: 'Language',
    spanish: 'Español',
    portuguese: 'Português (Brasil)',
    english: 'English (United States)',
    loading: 'Loading...',
    login: 'Sign in',
    email: 'Email *',
    password: 'Password *',
    remember: 'Remember me',
    forgotPassword: 'Forgot your password?',
    validating: 'Checking...',
    loginButton: 'SIGN IN',
    newBusiness: 'Are you a new business? Create your account',
    createAccountHere: 'Create your account here.',
    home: 'Home',
    pos: 'Point of Sale',
    workOrders: 'Work Orders',
    userManagement: 'User management',
    users: 'Users',
    roles: 'Roles',
    contacts: 'Customer/Supplier',
    suppliers: 'Suppliers',
    customers: 'Customers',
    customerGroups: 'Customer groups',
    products: 'Products',
    productList: 'Product list',
    addProduct: 'Add product',
    brands: 'Brands',
    categories: 'Categories',
    units: 'Units',
    purchases: 'Purchases',
    purchaseList: 'Purchase list',
    addPurchase: 'Add purchase',
    purchaseReturns: 'Purchase returns list',
    expenses: 'Expenses',
    expenseList: 'Expense list',
    addExpense: 'Add expense',
    expenseCategories: 'Expense categories',
    sales: 'Sales',
    allSales: 'All sales',
    pendingOrders: 'Pending orders',
    cashBank: 'Cash / Bank',
    cashRegisters: 'Cash registers',
    paymentReport: 'Payment cash report',
    reports: 'Reports',
    profitLoss: 'Profit and Loss',
    salesByProduct: 'Sales by product',
    salesCollections: 'Sales collections',
    cashRegister: 'Cash register',
    sellersCommissions: 'Sellers / Commissions',
    settings: 'Settings',
    companySettings: 'Company settings',
    commercialLocations: 'Business locations',
    invoiceSettings: 'Invoice settings',
    logout: 'Sign out',
    notifications: 'Notifications',
    realtimeData: 'Real-time data',
    noNotifications: 'No new notifications.',
    purchasePending: 'Pending purchase',
    openRegister: 'Open register',
    openedBy: 'Opened by',
    registerOpen: 'There is an open register',
    lowStock: 'Low stock',
    unitsLabel: 'units',
    collapseMenu: 'Collapse menu',
    expandMenu: 'Expand menu',
    notificationLabel: 'Notifications',
    manageCustomers: 'Manage your customers',
    filters: 'Filters',
    creditGranted: 'Credits granted',
    salesReturn: 'Sales return',
    paymentCompleted: 'Payment completed',
    creditBalance: 'Credit balance',
    customerGroup: 'Customer group',
    status: 'Status',
    allCustomers: 'All your customers',
    add: 'Add',
    show: 'Show',
    entries: 'entries',
    exportCsv: 'Export to CSV',
    exportExcel: 'Export to Excel',
    exportPdf: 'Export to PDF',
    print: 'Print',
    search: 'Search',
    noData: 'No data available in the table',
    companyLocation: 'Business location',
    purchaseStatus: 'Purchase status',
    paymentStatus: 'Payment status',
    allPurchases: 'All purchases',
    backToList: 'Back to list',
    registerNewPurchase: 'Register new purchase',
    selectProduct: 'Select product',
    saveAndAddStock: 'Save and add stock',
    noPurchases: 'No purchases registered.',
    allLocations: 'All locations',
    dateRange: 'Date range',
    allExpenses: 'All expenses',
    searchProduct: 'Search product',
    customerGroupName: 'Customer group name',
    all: 'All',
    electronicInvoicing: 'Electronic invoicing settings',
    loadingSellers: 'Loading sellers and commissions...',
    manageUsers: 'Manage users',
    allUsers: 'All users',
    username: 'Username',
    name: 'Name',
    role: 'Role',
    saveUser: 'Save user',
    loadingUsers: 'Loading users...',
    view: 'View',
    delete: 'Delete',
    previous: 'Previous',
    next: 'Next',
    userAdded: 'User added successfully',
    userDeleted: 'User deleted successfully.',
    saveError: 'There was an error saving. Check the console.',
    deleteError: 'There was an error deleting the user',
    cancel: 'Cancel',
    columnVisibility: 'Column visibility',
    action: 'Action',
    edit: 'Edit',
    showing: 'Showing',
    to: 'to',
    of: 'of',
    manageRoles: 'Manage roles',
    allRoles: 'All roles',
    noRoles: 'No roles registered.',
    roleNameRequired: 'The role name is required.',
    roleUpdated: 'Role updated successfully!',
    roleCreated: 'Role created successfully!',
    saveRoleError: 'Error saving role',
    editRole: 'Edit role',
    addRole: 'Add role',
    roleName: 'Role name',
    roleExample: 'E.g. Cashier',
    descriptionOptional: 'Description (optional)',
    selectAll: 'Select all',
    saving: 'Saving...',
    save: 'Save',
    editUser: 'Edit user',
    addUser: 'Add user',
    titleExample: 'Mr., Mrs.',
    isActive: 'Is active?',
    allowAccess: 'Allow access',
    confirmPassword: 'Confirm password',
    accessLocations: 'Access locations',
    fixedBranch: 'Fixed branch',
    branchAccessHelp: 'This user will only see the stock, sales, and register for this branch.',
    select: 'Select',
    salesCommissionPercentage: 'Sales commission percentage (%)',
    maxSalesDiscountPercentage: 'Maximum sales discount percentage',
    allowSelectedContacts: 'Allow selected contacts',
    bankDetails: 'Bank details',
    hrDetails: 'Human resources management details',
    restrictedAccess: 'Restricted access',
    noModulePermission: 'Your role does not have permission to access this module.',
    backHome: 'Back to home',
    checkingOpenRegister: 'Checking for an open register...',
    loadingData: 'Loading live data...', businessSummary: 'Your business summary', totalSales: 'Total sales', profit: 'Profit', salesMinusCosts: 'sales - purchases - expenses', billToPay: 'Bills to pay', pendingSuppliers: 'pending with suppliers', period: 'for the period', totalPurchases: 'Total purchases', purchaseDebt: 'Purchase debt', creditsGranted: 'Credits granted', openRegisters: 'Open registers', autoRefresh: 'Refreshes every 20 seconds - no page reload needed.', noOpenRegisters: 'There are no open registers at this time.', forceCloseHelp: 'Close this register if it was left open by mistake', forceClose: 'Force close', cash: 'Cash', card: 'Card',
    vsPreviousPeriod: 'vs previous period', noSalesPeriod: 'No sales in this period.', composition: 'Composition', noDataPeriod: 'No data for this period.', salesPurchasesExpenses: 'Sales vs Purchases vs Expenses', topProducts: 'Top 5 products', noDetailedSales: 'There are no detailed sales in this period yet.', recommendations: 'Recommendations for your business', currentFiscalYear: 'Current fiscal year sales', accountsReceivable: 'Accounts receivable', accountsPayable: 'Accounts payable', noReceivables: 'No accounts receivable.', invoiceNumber: 'Invoice No.', amountDue: 'Amount due', noPayables: 'No supplier debts.', invoice: 'Invoice', amount: 'Amount', stockGood: 'Your stock is at a good level.', stock: 'Stock',
    newCustomer: 'New customer', searchProductSku: 'Enter product name / SKU / barcode', advancedOptions: 'Advanced options', discount: 'Discount', packagingCharge: 'Packaging charge', serviceSeller: 'Service staff / seller', selectServiceSeller: 'Select service staff', saleNote: 'Sale note', product: 'Product', quantityShort: 'Qty.', unitPriceShort: 'Unit price', subtotal: 'Subtotal', emptyCart: 'The cart is empty', items: 'Items', total: 'Total', paidWith: 'Paid with', paymentMethod: 'Payment method', transferShort: 'Transfer', charge: 'Charge', change: 'Change', remainingDebt: 'Remaining balance', pendingOrder: 'Pending order', quote: 'Quote', creditSale: 'Credit sale', multiplePayment: 'Multiple payment',
    productType: 'Product type', stockStatus: 'Stock status', withStock: 'In stock', withoutStock: 'Out of stock', lowStockThreshold: 'Low stock (below alert threshold)', notForSale: 'Not for sale', onlyBelowAlert: 'Only below alert threshold', min: 'min.', max: 'max.', woocommerceEnabled: 'Woocommerce enabled', image: 'Image', unitPurchasePrice: 'Unit purchase price', salePrice: 'Sale price', currentStock: 'Current stock', noMatchingProducts: 'No product matches the search criteria.', labels: 'Labels', initialStock: 'Add or edit initial stock', stockHistory: 'Stock history', groupPrices: 'Group prices', duplicateProduct: 'Duplicate product', noProductMovements: 'This product has no registered sales or purchases yet.', productUpdated: 'Product updated successfully!', productSaved: 'Product saved successfully!', editProduct: 'Edit product', addNewProduct: 'Add new product', productInformation: 'Product information', productName: 'Product name', skuBarcodeType: 'SKU/Barcode / Barcode type', select: 'Select', subcategory: 'Subcategory', warranty: 'Warranty', selectAvailableLocations: 'Select which branches it will be available in',
    birthDate: 'Date of birth', gender: 'Gender', maritalStatus: 'Marital status', bloodType: 'Blood type', mobilePhone: 'Mobile phone number', dataAndType: 'Data and type (description, brochure, stock)', productDescription: 'Product description', productBrochure: 'Product brochure', selectFile: 'Select file', noFileSelected: 'No file selected', stockAndAlerts: 'Stock and alerts', manageStockQuestion: 'Manage stock?', yes: 'Yes', alertQuantity: 'Alert quantity', expiresIn: 'Expires in', pricesAndTaxes: 'Prices and taxes', applicableTax: 'Applicable tax', salePriceTaxType: 'Tax type on sale price', defaultPurchasePrice: 'Default purchase price', defaultSalePrice: 'Default sale price', taxNotIncluded: 'Tax not included', taxIncluded: 'Tax included',
    manageSuppliers: 'Manage your suppliers', purchaseReturn: 'Purchase return', seller: 'Seller', allSuppliers: 'All your suppliers', loadingSuppliers: 'Loading suppliers...', noSuppliers: 'No suppliers found.', actions: 'Actions', editSupplier: 'Edit supplier', addSupplier: 'Add supplier', contactType: 'Contact type', bothContacts: 'Both (Supplier and Customer)', companyName: 'Company name', representativeName: 'Representative name', documentNumber: 'Document No.', paymentTermDays: 'Payment term (days)', openingBalance: 'Opening balance', address: 'Address', supplierDetails: 'Supplier details', code: 'Code', company: 'Company', representative: 'Representative', paymentTerm: 'Payment term', days: 'days', saveChanges: 'Save changes',
    salesPos: 'Sales / Point of Sale',
    viewCustomers: 'View customers', addCustomer: 'Add customer', editCustomer: 'Edit customer', deleteCustomer: 'Delete customer', viewSuppliers: 'View suppliers', addSupplier: 'Add supplier', editSupplier: 'Edit supplier', deleteSupplier: 'Delete supplier', viewUsers: 'View users', addUserPermission: 'Add user', editUserPermission: 'Edit user', deleteUserPermission: 'Delete user', viewRoles: 'View roles', addRolePermission: 'Add role', editRolePermission: 'Edit role', deleteRolePermission: 'Delete role', viewProducts: 'View products', addProductPermission: 'Add product', editProductPermission: 'Edit product', deleteProductPermission: 'Delete product', viewBrands: 'View brands', viewUnits: 'View units', viewPurchasePrices: 'View purchase prices', viewPurchases: 'View purchases', addPurchasePermission: 'Add purchase', editPurchasePermission: 'Edit purchase', deletePurchasePermission: 'Delete purchase', viewSupplierDebts: 'View supplier debts', accessPos: 'Access Point of Sale', posOnly: 'Point of Sale only (blocks everything else)', applyDiscounts: 'Apply discounts', registerCreditSale: 'Register credit sale', editPrice: 'Edit price manually', viewOtherSales: 'View other users sales', openCash: 'Open register', closeCash: 'Close register', registerShiftExpenses: 'Register shift expenses', viewCashHistory: 'View cash register (history)', viewExpenses: 'View expenses', addExpensePermission: 'Add expense', viewProfitLoss: 'View Profit and Loss', viewCashRegister: 'View cash register', exportReports: 'Export reports (CSV/Excel/PDF)', accessGeneralSettings: 'Access general system settings', viewWorkOrders: 'View work orders', createWorkOrder: 'Create work order', editWorkOrder: 'Edit work order', deleteWorkOrder: 'Delete work order', viewLocations: 'View locations', manageLocations: 'Manage locations',
    prefix: 'Prefix',
    lastName: 'Last name',
    rolesPermissions: 'Roles and permissions',
    usernameAuto: 'Leave blank to generate the username automatically',
    financialData: 'Financial data',
    openCashRegister: 'Open cash register',
    enterOpeningBalance: 'Enter the opening cash balance',
    branch: 'Branch',
    selectBranch: 'Select a branch',
    noBranchAssigned: 'No branch assigned',
    cashInBaseCurrency: 'Cash in base currency',
    enterAmount: 'Enter amount',
    opening: 'Opening...',
    openRegisterButton: 'Open register',
    dateLocale: 'en-US',
  },
};

const languageOptions = [
  { value: 'es', labelKey: 'spanish' },
  { value: 'pt', labelKey: 'portuguese' },
  { value: 'en', labelKey: 'english' },
];

const databaseValueKeys = {
  Pagado: 'paid', 'Pago Parcial': 'partial', Pendiente: 'pending', 'A cobrar': 'toCollect',
  Abierta: 'open', Cerrada: 'closed', Activo: 'active', Inactivo: 'inactive',
  Efectivo: 'cash', Tarjeta: 'card', Transferencia: 'transfer', Cheque: 'check',
  Contado: 'cashSale', Crédito: 'credit', 'No incluido': 'notIncluded', Incluido: 'included',
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return translations[stored] ? stored : 'es';
  });

  const setLanguage = (nextLanguage) => {
    if (!translations[nextLanguage]) return;
    setLanguageState(nextLanguage);
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
  };

  useEffect(() => {
    document.documentElement.lang = translations[language].dateLocale;
  }, [language]);

  const value = {
    language,
    setLanguage,
    languageOptions,
    t: (key) => translations[language][key] || translations.es[key] || key,
        translateDbValue: (value) => {
          if (value === null || value === undefined || value === '') return value;
          const key = databaseValueKeys[value];
          return key ? (translations[language][key] || translations.es[key] || value) : value;
        },
      paid: 'Pagado', partial: 'Pago parcial', pending: 'Pendiente', toCollect: 'A cobrar', open: 'Abierta', closed: 'Cerrada', active: 'Activo', inactive: 'Inactivo', transfer: 'Transferencia', check: 'Cheque', cashSale: 'Contado', credit: 'Crédito', notIncluded: 'No incluido', included: 'Incluido',
      paid: 'Pago', partial: 'Pagamento parcial', pending: 'Pendente', toCollect: 'A cobrar', open: 'Aberta', closed: 'Fechada', active: 'Ativo', inactive: 'Inativo', transfer: 'Transferência', check: 'Cheque', cashSale: 'À vista', credit: 'Crédito', notIncluded: 'Não incluído', included: 'Incluído',
      paid: 'Paid', partial: 'Partially paid', pending: 'Pending', toCollect: 'To collect', open: 'Open', closed: 'Closed', active: 'Active', inactive: 'Inactive', transfer: 'Transfer', check: 'Check', cashSale: 'Cash', credit: 'Credit', notIncluded: 'Not included', included: 'Included',
    locale: translations[language].dateLocale,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}

export function LanguageSelector({ compact = false }) {
  const { language, setLanguage, languageOptions, t } = useLanguage();

  return (
    <label className={`flex items-center gap-2 text-xs ${compact ? 'text-gray-500' : 'text-gray-600'}`}>
      <span className="whitespace-nowrap">{t('language')}</span>
      <select
        value={language}
        onChange={(event) => setLanguage(event.target.value)}
        aria-label={t('language')}
        className="bg-white border border-gray-200 rounded-md px-2 py-1.5 text-xs text-gray-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
      >
        {languageOptions.map((option) => (
          <option key={option.value} value={option.value}>{t(option.labelKey)}</option>
        ))}
      </select>
    </label>
  );
}
