import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { Download, FileSpreadsheet, LoaderCircle, Pencil, Plus, Printer, Search, Tag, X } from 'lucide-react';
import { supabase } from './supabaseClient';
import { useEmpresaInfo } from './utils/useEmpresa';
import { useNotificacion } from './NotificacionContext';
import AperturaStock from './AperturaStock';

const Campo = ({ className = '', ...props }) => <input {...props} className={`w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-blue-500 ${className}`} />;
const Button = ({ children, className = '', ...props }) => <button {...props} className={`inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition disabled:opacity-50 ${className}`}>{children}</button>;
const money = (value) => `Gs ${Number(value || 0).toLocaleString('es-PY')}`;

export function ImprimirEtiquetasProductos() {
  const { id: empresaId } = useEmpresaInfo();
  const [productos, setProductos] = useState([]); const [busqueda, setBusqueda] = useState(''); const [elegidos, setElegidos] = useState({}); const [cargando, setCargando] = useState(true);
  useEffect(() => { if (!empresaId) return; supabase.from('productos').select('id,nombre,codigo,precio_venta').eq('empresa_id', empresaId).order('nombre').then(({ data }) => { setProductos(data || []); setCargando(false); }); }, [empresaId]);
  const filtrados = useMemo(() => productos.filter((p) => `${p.nombre} ${p.codigo || ''}`.toLowerCase().includes(busqueda.toLowerCase())), [productos, busqueda]);
  const seleccionados = productos.filter((p) => Number(elegidos[p.id]) > 0);
  const cambiar = (id, cantidad) => setElegidos((actual) => ({ ...actual, [id]: Math.max(0, Number(cantidad) || 0) }));
  const imprimir = () => { if (seleccionados.length) window.print(); };
  return <div className="space-y-5 p-4 md:p-6">
    <style>{`@page{size:letter;margin:8mm}@media print{body *{visibility:hidden!important}#etiquetas-print,#etiquetas-print *{visibility:visible!important}#etiquetas-print{position:fixed;inset:0;width:100%;padding:0;background:white}.etiquetas-controles{display:none!important}.etiquetas-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:3mm}.etiqueta{height:30mm;break-inside:avoid;page-break-inside:avoid;box-shadow:none!important}}`}</style>
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Productos</p><h1 className="text-2xl font-bold text-slate-900">Imprimir etiquetas</h1><p className="mt-1 text-sm text-slate-500">Seleccioná productos y cantidad de etiquetas para imprimir.</p></div><Button onClick={imprimir} disabled={!seleccionados.length} className="bg-orange-500 text-white hover:bg-orange-600"><Printer size={16}/> Imprimir ({Object.values(elegidos).reduce((s, n) => s + Number(n || 0), 0)})</Button></header>
    <section className="etiquetas-controles rounded-xl border bg-white p-4 shadow-sm"><label className="mb-3 flex max-w-md items-center gap-2 rounded-lg border px-3"><Search size={16} className="text-slate-400"/><Campo value={busqueda} onChange={(e) => setBusqueda(e.target.value)} placeholder="Buscar por producto o código" className="border-0 px-0 focus:border-0"/></label><div className="max-h-[48vh] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-100 text-xs uppercase text-slate-500"><tr><th className="p-3">Producto</th><th className="p-3">Código</th><th className="p-3">Precio</th><th className="w-32 p-3">Etiquetas</th></tr></thead><tbody className="divide-y">{filtrados.map((p) => <tr key={p.id}><td className="p-3 font-medium">{p.nombre}</td><td className="p-3 text-slate-500">{p.codigo || '—'}</td><td className="p-3">{money(p.precio_venta)}</td><td className="p-3"><Campo type="number" min="0" max="500" value={elegidos[p.id] || ''} onChange={(e) => cambiar(p.id, e.target.value)} placeholder="0"/></td></tr>)}</tbody></table>{cargando && <p className="p-6 text-center text-slate-400">Cargando productos...</p>}</div></section>
    <section id="etiquetas-print" className="rounded-xl border bg-white p-4"><h2 className="mb-3 flex items-center gap-2 font-bold text-slate-800"><Tag size={17}/> Vista previa</h2><div className="etiquetas-grid grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{seleccionados.flatMap((p) => Array.from({ length: Math.min(Number(elegidos[p.id]), 500) }, (_, i) => <article className="etiqueta flex h-28 flex-col justify-between rounded-lg border border-dashed border-slate-400 p-3" key={`${p.id}-${i}`}><strong className="line-clamp-2 text-sm">{p.nombre}</strong><div className="flex items-end justify-between gap-2"><span className="font-bold">{money(p.precio_venta)}</span><span className="text-xs tracking-widest">{p.codigo || ''}</span></div></article>))}{!seleccionados.length && <p className="col-span-full py-8 text-center text-sm text-slate-400">Elegí productos para preparar las etiquetas.</p>}</div></section>
  </div>;
}

export function ImportarStockInicial() {
  const { id: empresaId } = useEmpresaInfo(); const [productos, setProductos] = useState([]); const [filas, setFilas] = useState([]); const [errores, setErrores] = useState([]); const [archivo, setArchivo] = useState(''); const [cargando, setCargando] = useState(true); const [confirmado, setConfirmado] = useState(false);
  useEffect(() => { if (!empresaId) return; supabase.from('productos').select('id,nombre,codigo,unidad,precio_compra,stock_actual,iva').eq('empresa_id', empresaId).order('nombre').then(({ data }) => { setProductos(data || []); setCargando(false); }); }, [empresaId]);
  const leerArchivo = async (file) => {
    setArchivo(file?.name || ''); setFilas([]); setErrores([]); setConfirmado(false); if (!file) return;
    try {
      const libro = XLSX.read(await file.arrayBuffer(), { type: 'array', cellDates: false });
      const filasCrudas = XLSX.utils.sheet_to_json(libro.Sheets[libro.SheetNames[0]], { header: 1, defval: '' }).filter((fila) => fila.some((celda) => String(celda).trim()));
      const indiceInicio = filasCrudas.length && /sku|c[oó]digo/i.test(String(filasCrudas[0][0])) ? 1 : 0;
      const porCodigo = new Map(productos.filter((p) => p.codigo).map((p) => [String(p.codigo).trim().toLowerCase(), p]));
      const nuevas = []; const avisos = [];
      filasCrudas.slice(indiceInicio).forEach((fila, indice) => {
        const codigo = String(fila[0] ?? '').trim().toLowerCase(); const cantidad = Number(fila[2]); const costo = Number(fila[3]); const producto = porCodigo.get(codigo);
        if (!producto) { avisos.push(`Fila ${indice + indiceInicio + 1}: no se encontró el código ${fila[0] || '(vacío)'}.`); return; }
        if (!Number.isFinite(cantidad) || cantidad <= 0) { avisos.push(`Fila ${indice + indiceInicio + 1}: la cantidad debe ser mayor a cero.`); return; }
        const tasaIva = Number(String(producto.iva || '').match(/\d+/)?.[0] || 10);
        const costoConIva = Number.isFinite(costo) && costo >= 0 ? Math.round(costo * (1 + tasaIva / 100)) : (producto.precio_compra || '');
        nuevas.push({ id: `${producto.id}-${indice}`, productoId: producto.id, nombre: producto.nombre, unidad: producto.unidad || 'UNID', cantidad, costoUnitarioConIva: costoConIva, expDate: '', nota: 'Importación de stock inicial' });
      });
      setFilas(nuevas); setErrores(avisos);
      if (!nuevas.length && !avisos.length) setErrores(['El archivo no contiene filas para importar.']);
    } catch (error) { setErrores([`No se pudo leer el archivo: ${error.message}`]); }
  };
  const descargarPlantilla = () => { const ws = XLSX.utils.aoa_to_sheet([['SKU/Código de barras', 'Ubicación (opcional)', 'Cantidad', 'Costo unitario (sin IVA)', 'Número de lote (opcional)', 'Fecha de caducidad (opcional)'], ['CODIGO-001', '', 10, 100000, '', '']]); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'Stock inicial'); XLSX.writeFile(wb, 'plantilla-stock-inicial.xlsx'); };
  return <div className="space-y-5 p-4 md:p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Productos</p><h1 className="text-2xl font-bold text-slate-900">Importar stock inicial</h1><p className="mt-1 text-sm text-slate-500">Carga una planilla, revisá las coincidencias y confirmá antes de sumar existencias.</p></div><Button onClick={descargarPlantilla} className="border border-slate-300 bg-white text-slate-700"><Download size={16}/> Descargar plantilla</Button></header>
    <section className="space-y-4 rounded-xl border bg-white p-5 shadow-sm"><label className="flex max-w-xl cursor-pointer items-center gap-3 rounded-lg border-2 border-dashed border-slate-300 p-5 hover:border-blue-400"><FileSpreadsheet className="text-emerald-600"/><span><strong className="block text-sm">Seleccionar archivo CSV o Excel</strong><small className="text-slate-500">Columnas: código, ubicación, cantidad, costo sin IVA, lote y vencimiento.</small></span><input type="file" accept=".csv,.xls,.xlsx" className="sr-only" onChange={(e) => leerArchivo(e.target.files?.[0])}/></label>{archivo && <p className="text-sm text-slate-600">Archivo: <strong>{archivo}</strong></p>}
      {errores.length > 0 && <div className="max-h-32 overflow-auto rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{errores.map((msg, i) => <p key={i}>{msg}</p>)}</div>}
      {filas.length > 0 && !confirmado && <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-500"><tr><th className="p-3">Producto</th><th className="p-3">Cantidad</th><th className="p-3">Costo unitario</th><th className="p-3">Stock actual</th></tr></thead><tbody className="divide-y">{filas.map((f) => { const p = productos.find((x) => x.id === f.productoId); return <tr key={f.id}><td className="p-3">{f.nombre} <span className="text-xs text-slate-400">{p?.codigo}</span></td><td className="p-3">{f.cantidad} {f.unidad}</td><td className="p-3">{money(f.costoUnitarioConIva)}</td><td className="p-3">{p?.stock_actual || 0}</td></tr>; })}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 border-t pt-4"><p className="text-sm text-amber-800">Se sumarán {filas.length} líneas al stock actual. Revisá la planilla antes de continuar.</p><Button onClick={() => setConfirmado(true)} className="bg-orange-500 text-white hover:bg-orange-600">Continuar a revisión final</Button></div></>}
    </section>
    {confirmado && <section className="rounded-xl border border-blue-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold text-slate-800">Revisión final de stock inicial</h2><Button onClick={() => setConfirmado(false)} className="border text-slate-600"><X size={15}/> Volver</Button></div><p className="mb-4 text-xs text-slate-500">El botón Guardar suma las cantidades a las existencias actuales y aplica el flujo de apertura de stock del sistema.</p><AperturaStock key={archivo} filasIniciales={filas} compacto onGuardado={() => { setFilas([]); setArchivo(''); setConfirmado(false); }} onCancelar={() => setConfirmado(false)}/></section>}
    {cargando && <p className="text-sm text-slate-400">Cargando productos...</p>}
  </div>;
}

export function GruposPreciosVenta() {
  const { id: empresaId } = useEmpresaInfo(); const [productos, setProductos] = useState([]); const [busqueda, setBusqueda] = useState(''); const [producto, setProducto] = useState(null); const [grupos, setGrupos] = useState([]); const [guardando, setGuardando] = useState(false); const [error, setError] = useState('');
  const cargar = async () => { if (!empresaId) return; const { data, error: err } = await supabase.from('productos').select('id,nombre,codigo,precio_venta,grupos_precio').eq('empresa_id', empresaId).order('nombre'); if (err) setError(`No se pudieron cargar los grupos de precios: ${err.message}`); else { setError(''); setProductos(data || []); } };
  useEffect(() => { cargar(); }, [empresaId]);
  const filtrados = productos.filter((p) => `${p.nombre} ${p.codigo || ''} ${(p.grupos_precio || []).map((g) => g.nombre).join(' ')}`.toLowerCase().includes(busqueda.toLowerCase()));
  const editar = (p) => { setProducto(p); setGrupos(Array.isArray(p.grupos_precio) ? p.grupos_precio.map((g) => ({ ...g })) : []); };
  const guardar = async (e) => { e.preventDefault(); setGuardando(true); setError(''); const payload = grupos.filter((g) => g.nombre?.trim()).map((g) => ({ nombre: g.nombre.trim(), margen: Number(g.margen) || 0, precioVenta: Math.max(0, Math.round(Number(g.precioVenta) || 0)) })); const { error: err } = await supabase.from('productos').update({ grupos_precio: payload }).eq('id', producto.id).eq('empresa_id', empresaId); setGuardando(false); if (err) { setError(`No se pudo guardar: ${err.message}. Verificá database/migration_grupos_precio.sql.`); return; } setProducto(null); await cargar(); };
  return <div className="space-y-5 p-4 md:p-6"><header><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Productos</p><h1 className="text-2xl font-bold text-slate-900">Grupo de precios de venta</h1><p className="mt-1 text-sm text-slate-500">Administrá el precio especial de cada producto por grupo de cliente.</p></header>{error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="rounded-xl border bg-white p-4 shadow-sm"><label className="mb-4 flex max-w-md items-center gap-2 rounded-lg border px-3"><Search size={16} className="text-slate-400"/><Campo value={busqueda} onChange={(e) => setBusqueda(e.target.value)} placeholder="Buscar productos o grupos" className="border-0 px-0"/></label><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-500"><tr><th className="p-3">Producto</th><th className="p-3">Precio base</th><th className="p-3">Grupos y precios</th><th className="p-3 text-right">Acción</th></tr></thead><tbody className="divide-y">{filtrados.map((p) => <tr key={p.id}><td className="p-3 font-medium">{p.nombre}<small className="block text-slate-400">{p.codigo || '—'}</small></td><td className="p-3">{money(p.precio_venta)}</td><td className="p-3"><div className="flex flex-wrap gap-1">{(p.grupos_precio || []).map((g) => <span key={g.nombre} className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{g.nombre}: {money(g.precioVenta)}</span>)}{!p.grupos_precio?.length && <span className="text-xs text-slate-400">Sin precios por grupo</span>}</div></td><td className="p-3 text-right"><Button onClick={() => editar(p)} className="border border-slate-300 bg-white text-slate-700"><Pencil size={14}/> Editar</Button></td></tr>)}</tbody></table></div></section>
    {producto && <div className="fixed inset-0 z-[80] grid place-items-center overflow-y-auto bg-slate-950/50 p-3"><form onSubmit={guardar} className="my-auto w-full max-w-2xl space-y-4 rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-start justify-between"><div><h2 className="font-bold">Precios por grupo</h2><p className="text-sm text-slate-500">{producto.nombre} · precio base {money(producto.precio_venta)}</p></div><button type="button" onClick={() => setProducto(null)} aria-label="Cerrar"><X size={18}/></button></div>{grupos.map((g, i) => <div key={`${g.nombre}-${i}`} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-[1fr_120px_1fr_auto]"><Campo value={g.nombre || ''} placeholder="Nombre del grupo" onChange={(e) => setGrupos((xs) => xs.map((x, j) => j === i ? { ...x, nombre: e.target.value } : x))}/><Campo type="number" value={g.margen ?? 0} placeholder="Margen %" onChange={(e) => setGrupos((xs) => xs.map((x, j) => j === i ? { ...x, margen: e.target.value } : x))}/><Campo type="number" min="0" value={g.precioVenta ?? ''} placeholder="Precio de venta" onChange={(e) => setGrupos((xs) => xs.map((x, j) => j === i ? { ...x, precioVenta: e.target.value } : x))}/><Button type="button" onClick={() => setGrupos((xs) => xs.filter((_, j) => j !== i))} className="border text-red-600">Quitar</Button></div>)}<Button type="button" onClick={() => setGrupos((xs) => [...xs, { nombre: '', margen: 0, precioVenta: producto.precio_venta }])} className="border text-slate-700"><Plus size={15}/> Agregar grupo</Button><div className="flex justify-end gap-2 border-t pt-3"><Button type="button" onClick={() => setProducto(null)} className="border text-slate-600">Cancelar</Button><Button disabled={guardando} className="bg-slate-900 text-white">{guardando ? <LoaderCircle size={16} className="animate-spin"/> : 'Guardar precios'}</Button></div></form></div>}
  </div>;
}

export function GarantiasProductos() {
  const { id: empresaId } = useEmpresaInfo(); const { notificar } = useNotificacion(); const [productos, setProductos] = useState([]); const [garantia, setGarantia] = useState(''); const [seleccion, setSeleccion] = useState([]); const [busqueda, setBusqueda] = useState(''); const [guardando, setGuardando] = useState(false); const [error, setError] = useState('');
  const cargar = async () => { if (!empresaId) return; const { data, error: err } = await supabase.from('productos').select('id,nombre,codigo,garantia').eq('empresa_id', empresaId).order('nombre'); if (err) setError(err.message); else { setError(''); setProductos(data || []); } };
  useEffect(() => { cargar(); }, [empresaId]);
  const resumen = useMemo(() => [...new Set(productos.map((p) => p.garantia).filter(Boolean))].sort().map((nombre) => ({ nombre, cantidad: productos.filter((p) => p.garantia === nombre).length })), [productos]);
  const asignar = async (e) => { e.preventDefault(); if (!garantia.trim() || !seleccion.length) return; setGuardando(true); const { error: err } = await supabase.from('productos').update({ garantia: garantia.trim() }).eq('empresa_id', empresaId).in('id', seleccion); setGuardando(false); if (err) { setError(`No se pudo asignar la garantía: ${err.message}`); return; } setSeleccion([]); setGarantia(''); notificar.exito('Garantía asignada a los productos seleccionados.'); await cargar(); };
  const filtrados = productos.filter((p) => `${p.nombre} ${p.codigo || ''} ${p.garantia || ''}`.toLowerCase().includes(busqueda.toLowerCase()));
  return <div className="space-y-5 p-4 md:p-6"><header><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Productos</p><h1 className="text-2xl font-bold text-slate-900">Garantías</h1><p className="mt-1 text-sm text-slate-500">Revisá las garantías usadas y asigná una a varios productos.</p></header>{error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{resumen.map((g) => <div key={g.nombre} className="rounded-xl border bg-white p-4 shadow-sm"><p className="font-bold text-slate-800">{g.nombre}</p><p className="mt-1 text-sm text-slate-500">{g.cantidad} productos</p></div>)}{!resumen.length && <p className="text-sm text-slate-400">Todavía no hay garantías asignadas.</p>}</div><form onSubmit={asignar} className="grid gap-3 rounded-xl border bg-white p-4 shadow-sm md:grid-cols-[1fr_auto]"><label className="text-xs font-semibold text-slate-600">Garantía para los productos seleccionados<Campo value={garantia} onChange={(e) => setGarantia(e.target.value)} list="garantias-sugeridas" placeholder="Ej.: 6 meses" className="mt-1"/><datalist id="garantias-sugeridas"><option value="Sin garantía"/><option value="30 días"/><option value="3 meses"/><option value="6 meses"/><option value="1 año"/>{resumen.map((g) => <option key={g.nombre} value={g.nombre}/>)}</datalist></label><Button disabled={!seleccion.length || !garantia.trim() || guardando} className="self-end bg-slate-900 text-white">{guardando ? 'Guardando...' : `Asignar (${seleccion.length})`}</Button></form><section className="rounded-xl border bg-white p-4 shadow-sm"><label className="mb-4 flex max-w-md items-center gap-2 rounded-lg border px-3"><Search size={16} className="text-slate-400"/><Campo value={busqueda} onChange={(e) => setBusqueda(e.target.value)} placeholder="Buscar producto o garantía" className="border-0 px-0"/></label><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-500"><tr><th className="p-3">Elegir</th><th className="p-3">Producto</th><th className="p-3">Código</th><th className="p-3">Garantía</th></tr></thead><tbody className="divide-y">{filtrados.map((p) => <tr key={p.id}><td className="p-3"><input type="checkbox" checked={seleccion.includes(p.id)} onChange={() => setSeleccion((xs) => xs.includes(p.id) ? xs.filter((id) => id !== p.id) : [...xs, p.id])}/></td><td className="p-3 font-medium">{p.nombre}</td><td className="p-3 text-slate-500">{p.codigo || '—'}</td><td className="p-3">{p.garantia || <span className="text-slate-400">Sin asignar</span>}</td></tr>)}</tbody></table></div></section></div>;
}
